services:
  crud-py:
    build:
      context: ./python/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - py-net

  crud-ts:
    build:
      context: ./typescript/
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    networks:
      - ts-net

  crud-go:
    build:
      context: ./go/
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    networks:
      - go-net

  crud-rs:
    build:
      context: ./rust/
      dockerfile: Dockerfile
    ports:
      - 8003:8003
    networks:
      - rs-net

networks:
  py-net:
    driver: bridge
  ts-net:
    driver: bridge
  go-net:
    driver: bridge
  rs-net:
    driver: bridge
