[package]
name = "crud-api"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]

[profile.dev]
opt-level = 1

[profile.release]
strip = true
opt-level = "s"
overflow-checks = false
lto = true
codegen-units = 1
panic = "abort"
