name: CI

on:
  pull_request:

jobs:
  security:
    name: Scan apps security
    uses: ./.github/workflows/security.yml

  build:
    needs: security
    name: Build apps
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    name: Test apps
    uses: ./.github/workflows/test.yml
